config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  # Define the root route or routes
  root "exchange_rates#index"  # This will make the index page the homepage 

  resources :exchange_rates, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exchange_rate.rb
class ExchangeRate < ApplicationRecord
    def self.configure_rate_source(file_path, base_currency)
      CurrencyExchange.configure_rate_source(CurrencyExchange::JsonRateSource.new(file_path), base_currency)
    end
  
    def self.rate(date, from_currency, to_currency)
      CurrencyExchange.rate(date, from_currency, to_currency)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/exchange_rates_controller.rb
# This class handles the logic for displaying exchange rates 
# by processing user inputs(date, from_currency, to_currency),
# and fetching the correcponding exchange rate to user.

class ExchangeRatesController < ApplicationController

    # Method handles the logic when user visits the 'index' page.
    def index
        # Initialising the instance var to ensure it's empty at start.
        @rate = nil
        # Checking if user provided all params - date, from_currency, to_currency
        if params[:date].present? && params[:from_currency].present? && params[:to_currency].present?
            
            # Assign the provided params to local vars.
            date = params[:date]
            from_currency = params[:from_currency]
            to_currency = params[:to_currency]
   
            # Fetching exchange rate using CurrencyExchange module.
            begin
               @rate = CurrencyExchange.rate(date, from_currency, to_currency)
            rescue => e
                flash[:alert] = "Error fetching the exchange rate: #{e.message}"
            end
        else
          # If params are missing, a flash alert pops up to inform the user.
          flash[:alert] = "Please provide valid values for the Date, From Currency, and To Currency fields."
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchange_rates_helper.rb
module ExchangeRatesHelper
end

app/views/exchange_rates/index.html.erb
<h1 class="text-center">Exchange Rates</h1>

<section class="form-container">
  <%= form_with url: exchange_rates_path, method: :get, html: {class: 'exchange-rate-form' } do |f| %>
    <div class="form-group">
      <%= label_tag :date, "Date" %>
      <%= date_field_tag :date, nil %>
    </div>

    <div class="form-group">
      <%= label_tag :from_currency, "From Currency" %>
      <%= text_field_tag :from_currency, nil %>
    </div>
    
    <div class="form-group">
      <%= label_tag :to_currency, "To Currency" %>
      <%= text_field_tag :to_currency, nil %>
    </div>

    <div class="form-group text-center">
      <%= submit_tag "Get Rate", class: "btn btn-success" %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-warning">
      <%= flash[:alert] %>
    </div>
  <% end %>
</section>

<section class="output-container">
  <% if @rate %>
    <h2 class="text-center">Exchange Rate for 
    <span class="output-field"><%= params[:from_currency] %></span>
     to 
     <span class="output-field"><%= params[:to_currency] %></span> 
     on 
     <span class="output-field"><%= params[:date]%></span>
    </h2>
    <p class="text-center output-field"><%= @rate %></p>
  <% elsif @rate.nil? && flash[:alert].blank? %>
    <p class="text-center">No data found or please fill in the required fields.</p>
  <% end %>
</section>

<script>
document.addEventListener("DOMContentLoaded", function() {
  const form = document.querySelector(".exchange-rate-form");

  form.addEventListener("submit", function(event) {
    const dateField = form.querySelector("[name='date']");  
    if (!dateField.value) {
      event.preventDefault(); 
      alert("Please select the date.");
    }
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Currency Exchange" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>